import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      colors: {
        'primary':                    '#002444',
        'primary-container':          '#1a3a5c',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#87a4cc',
        'primary-fixed':              '#d2e4ff',
        'primary-fixed-dim':          '#abc9f2',
        'secondary':                  '#505f76',
        'secondary-container':        '#d0e1fb',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#54647a',
        'secondary-fixed':            '#d3e4fe',
        'secondary-fixed-dim':        '#b7c8e1',
        'tertiary':                   '#4f0003',
        'tertiary-container':         '#780007',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#ff796d',
        'surface':                    '#f8f9fb',
        'surface-bright':             '#f8f9fb',
        'surface-dim':                '#d9dadc',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f4f6',
        'surface-container':          '#edeef0',
        'surface-container-high':     '#e7e8ea',
        'surface-container-highest':  '#e1e2e4',
        'surface-variant':            '#e1e2e4',
        'surface-tint':               '#436084',
        'on-surface':                 '#191c1e',
        'on-surface-variant':         '#43474e',
        'background':                 '#f8f9fb',
        'on-background':              '#191c1e',
        'outline':                    '#73777f',
        'outline-variant':            '#c3c6cf',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
        'inverse-surface':            '#2e3132',
        'inverse-on-surface':         '#f0f1f3',
        'inverse-primary':            '#abc9f2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '0.75rem',
      },
      boxShadow: {
        'ambient': '0 4px 20px -4px rgba(0, 36, 68, 0.04)',
        'ambient-md': '0 8px 20px -8px rgba(0, 36, 68, 0.08)',
        'ambient-lg': '0 12px 24px -12px rgba(0, 36, 68, 0.10)',
        'header': '0 4px 20px -10px rgba(0, 36, 68, 0.05)',
      },
    },
  },
  plugins: [],
}
export default config
